#include <kernel/inet.h>
#include <kernel/string.h>
#include <kernel/net/link.h>
#include <kernel/net/ip.h>
#include <kernel/net/udp.h>
#include <kernel/net/dhcp.h>

static uint8_t dhcp_buf[1500];

typedef struct __attribute__((__packed__)) {
	uint8_t operation; // 1 = request; 2 = reply
	uint8_t hw_type; // 1: ethernet
	uint8_t hw_address_len; // 6, mac
	uint8_t hops; // client sets to 0
	uint32_t xid; // identification field generated by the client, to allow it to match up the request with replies received from DHCP servers.
	uint16_t seconds; // seconds client has been waiting, essentially
	uint16_t flags; // 1 = broadcast
	IPAddress ciaddr; // client IP
	IPAddress yiaddr; // 'your' (client) IP
	IPAddress siaddr; // server IP
	IPAddress giaddr; // IP address of the first relay agent a request message traveled.
	MacAddress client_mac;
	char hw_addr_padding[10];
	char sname[64];
	char file[128];
	// options
} DHCPMessage;

void dhcp_message_type(uint8_t typ, uint8_t *buf) {
	buf[0] = 0x35;
	buf[1] = 1; // length
	buf[2] = typ;
}

void dhcp_discover() {
	DHCPMessage msg;
	msg.operation = 1;
	msg.hw_type = 1;
	msg.hw_address_len = 6;
	msg.hops = 0;
	msg.xid = 1;
	msg.seconds = 0;
	msg.flags = 0;

	IPAddress zero = new_ip(0, 0, 0, 0);
	msg.ciaddr = zero;
	msg.yiaddr = zero;
	msg.siaddr = zero;
	msg.giaddr = zero;
	msg.client_mac = current_mac();
	for (int i = 0; i < 10; i++) {
		msg.hw_addr_padding[i] = 0;
	}
	for (int i = 0; i < 64; i++) {
		msg.sname[i] = 0;
	}
	for (int i = 0; i < 128; i++) {
		msg.file[i] = 0;
	}

	memcpy(dhcp_buf, (void*)&msg, sizeof(msg));

	size_t buf_pos = sizeof(msg);
	dhcp_buf[buf_pos++] = 99; // magic cookie follows
	dhcp_buf[buf_pos++] = 130;
	dhcp_buf[buf_pos++] = 83;
	dhcp_buf[buf_pos++] = 99;
	dhcp_buf[buf_pos++] = 0x35; // type 35 -> discover
	dhcp_buf[buf_pos++] = 1;
	dhcp_buf[buf_pos++] = 1;
	dhcp_buf[buf_pos++] = 0x39; // maximum message size
	dhcp_buf[buf_pos++] = 2;
	dhcp_buf[buf_pos++] = 0x2;
	dhcp_buf[buf_pos++] = 0x40;
	dhcp_buf[buf_pos++] = 0x37; // parameter request list
	dhcp_buf[buf_pos++] = 7;
	dhcp_buf[buf_pos++] = 0x1; // subnet mask
	dhcp_buf[buf_pos++] = 0x3; // router
	dhcp_buf[buf_pos++] = 0x6; // dns
	dhcp_buf[buf_pos++] = 0xc; // hostname
	dhcp_buf[buf_pos++] = 0xf; // domain name
	dhcp_buf[buf_pos++] = 0x1c; // broadcast address
	dhcp_buf[buf_pos++] = 0x2a; // ntp servers
	dhcp_buf[buf_pos++] = 0x3d; // client identifier
	dhcp_buf[buf_pos++] = 7;
	dhcp_buf[buf_pos++] = 1;
	memcpy(dhcp_buf + buf_pos, (void*)&msg.client_mac, 6);
	buf_pos += 6;
	dhcp_buf[buf_pos++] = 0xFF; // end

	IPAddress broad = new_ip(255, 255, 255, 255);
	send_udp(zero, 68, broad, 67, dhcp_buf, buf_pos);
}

void receive_dhcp(uint8_t *data, size_t data_len) {
	DHCPMessage *msg = (DHCPMessage*) data;

	printf("Offered IP ");
	print_ip(&msg->yiaddr);
	printf("\n");
}